@host=http://localhost:5001/api/v1

GET {{host}}/animals HTTP/1.1
Accept: application/json

###

POST {{host}}/animals HTTP/1.1
Accept: application/json

{
    "id": "100",
    "type": "Dog",
    "name": "Doe"
}

###

GET {{host}}/animals/100 HTTP/1.1
Accept: application/json

###

DELETE {{host}}/animals/100 HTTP/1.1
Accept: application/json

