@host=http://localhost:5001/api/v1

GET {{host}}/users HTTP/1.1
Accept: application/json
Content-Type: application/json

###

POST {{host}}/users HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe"
}

###

GET {{host}}/users/67100ba6a11884efa9bd2fba HTTP/1.1
Accept: application/json

###

DELETE {{host}}/users/100 HTTP/1.1
Accept: application/json
