@host=http://localhost:5001/api/v1

GET {{host}}/users HTTP/1.1
Accept: application/json

###

POST {{host}}/users HTTP/1.1
Accept: application/json

{
    "firstName": "John",
    "lastName": "Doe"
}

###

GET {{host}}/users/66cf9a1b460ae5592cec8f2d HTTP/1.1
Accept: application/json

###

DELETE {{host}}/users/100 HTTP/1.1
Accept: application/json
