services:
  server:
    build:
      context: ./apps/backend
      dockerfile: ./Dockerfile
    environment:
      PORT: 8080
    ports:
      - 5001:8080
    networks:
      - app-network
    volumes:
      - ./apps/backend/src:/app/src
  
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: ./Dockerfile
    environment:
      VITE_GATEWAY_BACKEND: http://localhost:5001
    ports:
      - 5002:8080
    networks:
      - app-network
    volumes:
      - ./apps/frontend/src:/app/src

networks:
  app-network:
    driver: bridge
