services:
  server:
    build:
      context: ./apps/backend
      dockerfile: ./Dockerfile
    environment:
      PORT: 8080
    ports:
      - 5001:8080
    volumes:
      - ./apps/backend/src:/app/src
